CREATE TABLE funeral.producer(
    id_producer BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    producer_id BIGINT UNIQUE  NOT NULL,
    name VARCHAR NOT NULL
);

CREATE TABLE funeral.product_category(
    id_product_category BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    product_category_id BIGINT UNIQUE  NOT NULL,
    name VARCHAR NOT NULL
);

CREATE TABLE funeral.product(
    id_product BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    id_producer BIGINT NOT NULL REFERENCES funeral.producer (id_producer) ON UPDATE CASCADE,
    id_product_category BIGINT NOT NULL REFERENCES funeral.product_category(id_product_category) ON UPDATE CASCADE,
    product_id BIGINT UNIQUE,
    name VARCHAR NOT NULL,
    note VARCHAR,
    in_stock INT NOT NULL
);

CREATE TABLE funeral.product_movement(
    id_product_movement BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    id_product BIGINT NOT NULL REFERENCES funeral.product (id_product) ON UPDATE CASCADE,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    old_state INT NOT NULL,
    requested INT NOT NULL,
    new_state INT NOT NULL
);
