CREATE TABLE funeral.product_category(
    id_product_category BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    product_category_id BIGINT UNIQUE  NOT NULL,
    name VARCHAR NOT NULL
);

CREATE TABLE funeral.product(
    id_product BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    id_product_category BIGINT NOT NULL,
    product_id BIGINT UNIQUE,
    producer VARCHAR,
    type VARCHAR,
    name VARCHAR NOT NULL,
    comment VARCHAR,
    flagged BOOLEAN NOT NULL,
    in_stock INT NOT NULL,
    CONSTRAINT product_product_category_fk FOREIGN KEY (id_product_category) REFERENCES funeral.product_category (id_product_category) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE funeral.product_movement(
    id_product_movement BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    id_product BIGINT NOT NULL REFERENCES funeral.product (id_product) ON UPDATE CASCADE,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    old_state INT NOT NULL,
    requested INT NOT NULL,
    new_state INT NOT NULL,
    type VARCHAR NOT NULL,
    CONSTRAINT product_movement_product_fk FOREIGN KEY (id_product) REFERENCES funeral.product (id_product) ON UPDATE CASCADE ON DELETE CASCADE
);
