CREATE TABLE funeral.company(
    id_company BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    company_id BIGINT UNIQUE NOT NULL,
    id_office BIGINT,
    name VARCHAR NOT NULL,
    street VARCHAR NOT NULL,
    city VARCHAR NOT NULL,
    country VARCHAR,
    postal_code VARCHAR NOT NULL,
    phone VARCHAR NOT NULL,
    email VARCHAR,
    warehouseShared BOOLEAN NOT NULL,
    warehouseEnabled BOOLEAN NOT NULL
);

CREATE TABLE funeral.user(
    id_user BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id BIGINT NOT NULL,
    name VARCHAR NOT NULL,
    surname VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    email VARCHAR NOT NULL
);

CREATE TABLE funeral.company_user(
    id_user BIGINT NOT NULL,
    id_company BIGINT NOT NULL
);

INSERT INTO funeral.company (company_id, id_office, name, street, city, country, postal_code, phone, email, warehouseEnabled, warehouseShared)
VALUES (1, null, 'POSPÍCHAL POHŘEBNÍ SLUŽBA s.r.o.', 'Přímětická 12', 'Znojmo', 'Česká Republika', '66904', '515 226 009', null, true, true);

INSERT INTO funeral.user (user_id, name, surname, password, email)
VALUES (1, 'Test', 'Testovic', 'test', 'test@test.cz');

ALTER TABLE funeral.product_category ADD id_company BIGINT;
UPDATE funeral.product_category SET id_company = (SELECT id_company from funeral.company WHERE company_id = 1);
ALTER TABLE funeral.product_category ALTER COLUMN id_company SET NOT NULL;
ALTER TABLE funeral.product_category ADD CONSTRAINT product_category_company_fk FOREIGN KEY (id_company) REFERENCES funeral.company (id_company);

ALTER TABLE funeral.product ADD id_company BIGINT;
UPDATE funeral.product SET id_company = (SELECT id_company from funeral.company WHERE company_id = 1);
ALTER TABLE funeral.product ALTER COLUMN id_company SET NOT NULL;
ALTER TABLE funeral.product ADD CONSTRAINT product_company_fk FOREIGN KEY (id_company) REFERENCES funeral.company (id_company);

INSERT INTO funeral.company_user(id_user, id_company) VALUES (1,1);
